### PR TITLE
Mark external links with a trailing icon

### LINKED ISSUE #3: External link visual cue
Something similar to nextstrain.org/docs' symbols which indicate an external link in the sidebar (and in a document, but especially in the sidebar) would be helpful:

Screen Shot 2020-10-21 at 5 16 59 PM

### PR DESCRIPTION
**Pull request by tsibley**
Font Awesome (v4) is already included by the RTD theme and Sphinx
already tags external links with a class in the HTML.  Glue the two
together with some CSS.

Resolves #3.

### CODE REVIEW

**Comment by eharkins** [comment]
I guess the build just failed because it's not on top of #11. Once we merge that, the build should work and we can preview it, correct?

**Comment by tsibley** [comment]
Yes, except we don't have any external links in the sidebar of this project to preview, I think. Something like the [RTD theme's demo documentation](https://sphinx-rtd-theme.readthedocs.io/en/stable/) showing how every thing renders would be useful here, but it was more work than I wanted to take on right now since I'm already several yaks deep.

**Comment by tsibley** [comment]
@eharkins Ok, so I shaved another (very small) yak and added a "demo doc" section showing the external link styling: https://nextstrain-sphinx-theme--12.org.readthedocs.build/en/12/index.html

**Review by eharkins — APPROVED** [review]
Looks great @tsibley! And thanks for adding the example doc!

**Pull request merged**
